In [1]:
import pandas as pd

In [2]:
!pip install imblearn

In [3]:
dataset = pd.read_csv('creditcard.csv')

In [4]:
df = dataset.sample(n = 10000,random_state = 42)
print(df[df['Class'] == 1]['Class'].shape,df[df['Class'] == 0]['Class'].shape,df.shape)

(16,) (9984,) (10000, 31)


In [5]:
x = df.drop('Class',axis = 1)
y = df['Class']
x

Time         V1        V2         V3        V4         V5  \
43428    41505.0 -16.526507  8.584972 -18.649853  9.505594 -13.793819   
49906    44261.0   0.339812 -2.743745  -0.134070 -1.385729  -1.451413   
29474    35484.0   1.399590 -0.590701   0.168619 -1.029950  -0.539806   
276481  167123.0  -0.432071  1.647895  -1.669361 -0.349504   0.785785   
278846  168473.0   2.014160 -0.137394  -1.015839  0.327269  -0.182179   
...          ...        ...       ...        ...       ...        ...   
240378  150578.0  -0.954519  0.992190  -0.847651 -1.581983   0.715487   
111987   72467.0   1.622073 -0.865882  -0.538933 -1.524359  -0.799222   
210990  138215.0  -1.482246 -0.517592   1.187354 -3.104914  -0.827490   
97524    66258.0  -0.615090  1.354411   0.580766 -0.094208   0.114572   
98359    66629.0  -0.476832  1.001665   1.672802 -0.004422  -0.053953   

              V6         V7        V8        V9  ...       V20       V21  \
43428  -2.832404 -16.701694  7.517344 -8.507059  ... -1.514923  1.190739   
49906   1.015887  -0.524379  0.224060  0.899746  ...  0.506044 -0.213436   
29474   0.040444  -0.712567  0.002299 -0.971747  ...  0.212877  0.102398   
276481 -0.630647   0.276990  0.586025 -0.484715  ... -0.244633  0.358932   
278846 -0.956571   0.043241 -0.160746  0.363241  ... -0.255293 -0.238644   
...          ...        ...       ...       ...  ...       ...       ...   
240378  0.307996  -0.309704 -3.421758 -0.868249  ... -1.311719  3.104242   
111987 -0.894892  -0.528204 -0.315828 -2.000084  ... -0.379820 -0.239334   
210990 -0.198460  -0.342515  0.260517 -1.958345  ... -0.489290 -0.231974   
97524  -0.570746   0.305109  0.422723 -0.468357  ...  0.008504 -0.281457   
98359  -0.619122   0.622558  0.058973 -0.401058  ...  0.043570 -0.181100   

             V22       V23       V24       V25       V26       V27       V28  \
43428  -1.127670 -2.358579  0.673461 -1.413700 -0.462762 -2.018575 -1.042804   
49906  -0.942525 -0.526819 -1.156992  0.311211 -0.746647  0.040996  0.102038   
29474   0.168269 -0.166639 -0.810250  0.505083 -0.232340  0.011409  0.004634   
276481  0.873663 -0.178642 -0.017171 -0.207392 -0.157756 -0.237386  0.001934   
278846 -0.616400  0.347045  0.061561 -0.360196  0.174730 -0.078043 -0.070571   
...          ...       ...       ...       ...       ...       ...       ...   
240378 -0.085788 -0.021165  0.039500 -0.053577  0.014108  0.441098  0.209279   
111987 -0.323156 -0.172190 -0.470333  0.762596 -0.028195 -0.009995 -0.004150   
210990 -0.056937 -0.137343 -0.538200  0.716969 -0.139928 -0.184491 -0.244904   
97524  -0.873740 -0.069198 -0.513659 -0.033854  0.127282  0.119022  0.026056   
98359  -0.430898  0.046890  0.377464 -0.315426  0.081162  0.281740  0.120515   

        Amount  
43428   364.19  
49906   520.12  
29474    31.00  
276481    1.50  
278846    0.89  
...        ...  
240378   28.67  
111987   12.00  
210990   54.60  
97524     0.05  
98359     1.79  

[10000 rows x 30 columns]

In [6]:
print(x.shape,y.shape)

(10000, 30) (10000,)


0 = Real 1 = Fraud

In [7]:
import numpy as np
df[df['Class'] == 0]

Time        V1        V2        V3        V4        V5        V6  \
49906    44261.0  0.339812 -2.743745 -0.134070 -1.385729 -1.451413  1.015887   
29474    35484.0  1.399590 -0.590701  0.168619 -1.029950 -0.539806  0.040444   
276481  167123.0 -0.432071  1.647895 -1.669361 -0.349504  0.785785 -0.630647   
278846  168473.0  2.014160 -0.137394 -1.015839  0.327269 -0.182179 -0.956571   
101565   67878.0 -0.641330 -0.057304  1.489998 -1.688131 -1.151043  0.259996   
...          ...       ...       ...       ...       ...       ...       ...   
240378  150578.0 -0.954519  0.992190 -0.847651 -1.581983  0.715487  0.307996   
111987   72467.0  1.622073 -0.865882 -0.538933 -1.524359 -0.799222 -0.894892   
210990  138215.0 -1.482246 -0.517592  1.187354 -3.104914 -0.827490 -0.198460   
97524    66258.0 -0.615090  1.354411  0.580766 -0.094208  0.114572 -0.570746   
98359    66629.0 -0.476832  1.001665  1.672802 -0.004422 -0.053953 -0.619122   

              V7        V8        V9  ...       V21       V22       V23  \
49906  -0.524379  0.224060  0.899746  ... -0.213436 -0.942525 -0.526819   
29474  -0.712567  0.002299 -0.971747  ...  0.102398  0.168269 -0.166639   
276481  0.276990  0.586025 -0.484715  ...  0.358932  0.873663 -0.178642   
278846  0.043241 -0.160746  0.363241  ... -0.238644 -0.616400  0.347045   
101565 -1.391069 -2.334075  1.168644  ... -1.231634  0.257164 -0.371953   
...          ...       ...       ...  ...       ...       ...       ...   
240378 -0.309704 -3.421758 -0.868249  ...  3.104242 -0.085788 -0.021165   
111987 -0.528204 -0.315828 -2.000084  ... -0.239334 -0.323156 -0.172190   
210990 -0.342515  0.260517 -1.958345  ... -0.231974 -0.056937 -0.137343   
97524   0.305109  0.422723 -0.468357  ... -0.281457 -0.873740 -0.069198   
98359   0.622558  0.058973 -0.401058  ... -0.181100 -0.430898  0.046890   

             V24       V25       V26       V27       V28  Amount  Class  
49906  -1.156992  0.311211 -0.746647  0.040996  0.102038  520.12      0  
29474  -0.810250  0.505083 -0.232340  0.011409  0.004634   31.00      0  
276481 -0.017171 -0.207392 -0.157756 -0.237386  0.001934    1.50      0  
278846  0.061561 -0.360196  0.174730 -0.078043 -0.070571    0.89      0  
101565 -0.038566  1.397514 -0.665947  0.031003  0.180357  100.00      0  
...          ...       ...       ...       ...       ...     ...    ...  
240378  0.039500 -0.053577  0.014108  0.441098  0.209279   28.67      0  
111987 -0.470333  0.762596 -0.028195 -0.009995 -0.004150   12.00      0  
210990 -0.538200  0.716969 -0.139928 -0.184491 -0.244904   54.60      0  
97524  -0.513659 -0.033854  0.127282  0.119022  0.026056    0.05      0  
98359   0.377464 -0.315426  0.081162  0.281740  0.120515    1.79      0  

[9984 rows x 31 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 42)

In [9]:
print(x_train.shape,y_train.shape)

(7500, 30) (7500,)


##Handling Imbalanced Dataset

In [10]:
#clearing datasets finding any nan values
print(np.isnan(y_train).sum())     #returns no of rows with nan  np.isnan(y_train)-> converts y_train to a boolean array
print(np.where(np.isnan(y_train))) #print(y_train.iloc[6326]) = NaN
print(np.where(np.isnan(x_train)))
print(x_train.iloc[6326,:])

0
(array([], dtype=int64),)
(array([], dtype=int64), array([], dtype=int64))
Time      140103.000000
V1            -0.310111
V2             1.081641
V3            -0.862850
V4            -1.049064
V5             0.919428
V6            -1.755481
V7             1.619173
V8            -0.394141
V9             0.021091
V10           -0.134706
V11           -1.093855
V12           -0.902112
V13           -1.814178
V14            0.964424
V15            0.055326
V16           -0.670499
V17           -0.265441
V18           -0.299121
V19           -0.227589
V20           -0.045039
V21            0.205799
V22            0.800223
V23           -0.195103
V24           -0.004306
V25           -0.319271
V26            0.101180
V27            0.493044
V28            0.337608
Amount        16.000000
Name: 215508, dtype: float64


In [11]:
from sklearn.impute import SimpleImputer        #input = 2D array in numpy or Dataframe
si = SimpleImputer(strategy = 'most_frequent')
si.fit(pd.DataFrame(y_train))   #[[series]] = dataframe
y_train = si.transform(pd.DataFrame(y_train))
y_train = pd.Series(y_train.ravel(),name = 'Class')

In [12]:
print(np.isnan(y_train).sum())
print(np.isnan(x_train).sum())

0
Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
dtype: int64


In [13]:
print(type(y_train),y_train.shape)

<class 'pandas.core.series.Series'> (7500,)


In [14]:
print(y_train.iloc[:56])

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
52    0
53    0
54    0
55    0
Name: Class, dtype: int64


###Oversampling the Minority

In [15]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy = 'minority')
X_train,Y_train = smote.fit_resample(x_train,y_train)     #smote cant be applied with NaN values

In [16]:
from imblearn.over_sampling import ADASYN
ada = ADASYN(sampling_strategy = 'minority')
X_train_ad,Y_train_ad = ada.fit_resample(x_train,y_train)

In [17]:
print(X_train_ad.shape,Y_train_ad.shape)
print(Y_train_ad[Y_train_ad == 1].sum())

(14979, 30) (14979,)
7488


In [18]:
print(X_train.shape,Y_train.shape)
print(Y_train[Y_train == 1].sum())

(14982, 30) (14982,)
7491


###Undersampling the Majority

In [19]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(sampling_strategy = 'majority')
X_train_1,Y_train_1 = rus.fit_resample(x_train,y_train)

In [20]:
print(X_train_1.shape,Y_train_1.shape)

(18, 30) (18,)


In [21]:
print(X_train.iloc[:5,:])
print(Y_train[:5])

       Time        V1        V2        V3        V4        V5        V6  \
0  136147.0  1.476824 -1.827496 -0.924490 -0.005518 -1.056110  0.013391   
1   77438.0  0.604839 -1.886371 -0.554519 -0.174555 -1.244669 -0.729373   
2   54936.0 -2.171191  0.725919  0.773317 -2.700888 -1.949180  0.017771   
3   77427.0 -2.505528  0.659413  1.474736  0.299191 -1.342264  0.035586   
4   74524.0  0.908828 -1.404905  1.314052  0.959853 -1.777457  0.705762   

         V7        V8        V9  ...       V20       V21       V22       V23  \
0 -0.408247 -0.115788 -0.161869  ...  0.147249 -0.428233 -1.449095  0.203779   
1  0.263710 -0.323298 -0.663309  ...  0.313250 -0.226300 -1.065347 -0.412884   
2 -1.692170  1.625624 -2.457165  ... -0.287549  0.055547  0.311293 -0.173972   
3 -1.248463  1.682620  0.921556  ... -0.977579  0.285749  0.692987 -0.363822   
4 -1.157607  0.260878  0.600663  ... -0.212472 -0.337695 -0.480577 -0.215476   

        V24       V25       V26       V27       V28  Amount  
0  0.4

##Using SVM

###Scaling the Predictors

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_svc = sc.fit_transform(X_train)

In [23]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state = 42,class_weight='balanced')
classifier.fit(X_train_svc,Y_train)

SVC(class_weight='balanced', random_state=42)

In [24]:
print(np.isnan(x_test).sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
dtype: int64


In [25]:
Y_pred_svc = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,Y_pred_svc)
print(cm)
ac = accuracy_score(y_test,Y_pred_svc)
print(ac)

[[2493    0]
 [   7    0]]
0.9972


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


In [26]:
print(Y_pred_svc[Y_pred_svc == 1].sum())
print(y_test[y_test == 1].sum())

0
7


In [27]:
X_train_ad_svc = sc.fit_transform(X_train_ad)
classifier1 = SVC(kernel = 'rbf',random_state = 42,class_weight='balanced')
classifier1.fit(X_train_ad_svc,Y_train_ad)

SVC(class_weight='balanced', random_state=42)

In [28]:
Y_pred_ad_svc = classifier1.predict(x_test)
cm = confusion_matrix(y_test,Y_pred_ad_svc)
print(cm)
ac = accuracy_score(y_test,Y_pred_ad_svc)
print(ac)

[[2493    0]
 [   7    0]]
0.9972


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


Some algorithms handle imbalanced datasets better than others. Consider trying algorithms like Random Forest, XGBoost, or LightGBM, which often have parameters specifically for dealing with class imbalance.

#Using RandomForest

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state = 42,class_weight = 'balanced')
classifier_rf.fit(X_train,Y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [30]:
Y_pred_rf = classifier_rf.predict(x_test)
cm = confusion_matrix(y_test,Y_pred_rf)
print(cm)
ac = accuracy_score(y_test,Y_pred_rf)
print(ac)

[[2493    0]
 [   3    4]]
0.9988


##Visualization of data.

###Training model with 2 predictors using RFC

In [31]:
X_train.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount'],
      dtype='object')

In [32]:
classifier_rf2p = RandomForestClassifier(random_state = 42,class_weight = 'balanced')
predictors = ['Time','Amount']
classifier_rf2p.fit(X_train[predictors],Y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [33]:
Y_pred_rf2p = classifier_rf.predict(x_test)
cm = confusion_matrix(y_test,Y_pred_rf2p)
print(cm)
ac = accuracy_score(y_test,Y_pred_rf2p)
print(ac)

[[2493    0]
 [   3    4]]
0.9988


In [ ]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
X_set, y_set = np.array(X_train),np.array(Y_train)
x1,x2 = np.meshgrid(np.arange(start = X_set[:,0].min()-1000,stop = X_set[:,0].max()+1000,step = 1),
                    np.arange(start = X_set[:,-1].min()-1000,stop = X_set[:,-1].max()+1000,step = 1))
plt.contour(x1,x2,classifier_rf2p.predict(np.array([x1.ravel(),x2.ravel()]).T).reshape(x1.shape),
            alpha = 0.75,cmap = ListedColormap(('red','green')))
plt.xlim(x1.min(),x1.max())
plt.ylim(x2.min(),x2.max())
for i,j in enumerate(np.unique(y_set)):
  plt.scatter(X_set[y_set == j,0],X_set[y_set == j,-1],c = ListedColormap(('red','green'))(i),label = j)
plt.xlabel('Predictors')
plt.ylabel('Dependent Values')
plt.title('Plot for RFC')
plt.legend()
plt.show()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
